### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by JREAM** [SirCortly/ubuntu-post-install#1]
You should make a bash file, run once, boom!

I have a bunch of crap here you can copy!
- Server: https://github.com/JREAM/config-ubuntu/tree/master/bin/server
- Desktop: https://github.com/JREAM/config-ubuntu/tree/master/bin/desktop
- DevOps: https://github.com/JREAM/config-ubuntu/tree/master/bin/devops

I'd also recommend using Docker and Docker-Compose, then you won't have to have MongoDB or other services running all the time. I like ELK here: https://github.com/JREAM/docker-elk -- For Docker to get used to running things sometimes a GUI to start helps eg: https://github.com/docker/kitematic/releases or a web based interface https://github.com/portainer/portainer

I think you should use PHP7 also, Ubuntu 16.04 ships with it by default. 

## Sublime
Downside, requires version number
```
wget https://download.sublimetext.com/sublime-text_build-3126_amd64.deb
sudo dpkg -i sublime-text_build-3126_amd64.deb
rm sublime-text_build-3126_amd64.deb
```

## Chrome
```
sudo apt-get install -y libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
sudo dpkg -i google-chrome*.deb
sudo rm google-chrome*.deb
```

## Vagrant
Downside, requires version number
```
curl -o vagrant.deb https://releases.hashicorp.com/vagrant/1.9.2/vagrant_1.9.2_x86_64.deb
sudo dpkg -i vagrant.deb
rm vagrant.deb
```

**Comment by SirCortly** [comment]
Thanks for the suggestions @JREAM! This was an old repo that I had private but I downgraded my GitHub subscriptions so no more privates lol. I'm started to get ramped up here again so I will definitely follow your suggestions and get this thing up to date!
